"""Python files copied into the standalone .app. Keep in sync with tests."""

BUNDLE_PY = (
    "app.py",
    "app_env.py",
    "app_security.py",
    "app_jobs.py",
    "desktop.py",
    "rvc_engine.py",
    "rvc_train.py",
    "rvc_api.py",
    "vc_runner.py",
    "library.py",
    "exports.py",
    "remix.py",
    "diarize.py",
    "youtube_lib.py",
    "audio_io.py",
    "audio_text.py",
    "utils.py",
    "uvr_runtime.py",
    "mdx_model.py",
    "ui_widgets.py",
    "ui_status.py",
    "install_rvc_assets.py",
    "album_cover.py",
    "video_remux.py",
    "occupancy.py",
    "train_run.py",
    "train_prep.py",
    "gpu_secrets.py",
    "runpod_train.py",
    "gemini_cover.py",
    "bundle_py.py",
    "pwa_server.py",
)
